" =================
"  Kota VIMrc v1.1
" =================
"
" =================
"    Use Vundle
" =================
" Make vim the same on any os
set nocompatible

" Needed for Vundle
filetype off 

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" use color scheme
"Plugin 'morhetz/gruvbox'

" use nice airline plugin
"Plugin 'vim-airline/vim-airline'

" use airline themes
"Plugin 'vim-airline/vim-airline-themes'

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Really easy indenting
Plugin 'junegunn/vim-easy-align'

" Comment shit out easily
Plugin 'tpope/vim-commentary'

" Easily tweak tags and surroundings
Plugin 'tpope/vim-surround'

" Make <C-a> and <C-x> work with dates
Plugin 'tpope/vim-speeddating'

" Color for codes
Plugin 'ap/vim-css-color'

" Love docs and highlights
Plugin 'davisdude/vim-love-docs'

" You Complete Me - Vim Autocomplete Engine
Plugin 'Valloric/YouCompleteMe'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

" =================
"   Normal Config
" =================

" Enable syntax based on contents file-type + set colorscheme
" set termguicolors
syntax enable
"let g:airline_powerline_fonts = 1
"let g:gruvbox_termcolors=16
"colorscheme gruvbox

" use utf-8
set encoding=utf-8
 
" Work better on i3 for lots of files open 
set hidden
 
" Good command line completion 
set wildmenu
 
" Show partial commands in the last line of the screen
set showcmd
 
" Highlight searches (use <C-L> to temporarily turn off highlighting; see the
" mapping of <C-L> below)
set hlsearch
 
" Use case insensitive search, except when using capital letters
set ignorecase
set smartcase
 
" Allow backspacing over autoindent, line breaks and start of insert action
set backspace=indent,eol,start
 
" When opening a new line and no filetype-specific indenting is enabled, keep
" the same indent as the line you're currently on. Useful for READMEs, etc.
set autoindent
 
" Stop certain movements from always going to the first character of a line.
" While this behaviour deviates from that of Vi, it does what most users
" coming from other editors would expect.
set nostartofline
 
" Display the cursor position on the last line of the screen or in the status
" line of a window
set ruler
 
" Always display the status line, even if only one window is displayed
set laststatus=2
 
" Instead of failing a command because of unsaved changes, instead raise a
" dialogue asking if you wish to save changed files.
set confirm
 
" Use visual bell instead of beeping when doing something wrong
set visualbell

" And reset the terminal code for the visual bell. If visualbell is set, and
" this line is also included, vim will neither flash nor beep. If visualbell
" is unset, this does nothing.
set t_vb=

" Enable use of the mouse for all modes
set mouse=a
 
" Set the command window height to 2 lines, to avoid many cases of having to
" "press <Enter> to continue"
set cmdheight=2
 
" Display line numbers on the left
set number
 
" Quickly time out on keycodes, but never time out on mappings
set notimeout ttimeout ttimeoutlen=200
 
" Use <F11> to toggle between 'paste' and 'nopaste'
set pastetoggle=<F11>
 
" Indentation settings for using hard tabs for indent. Display tabs as
" four characters wide.
set shiftwidth=4
set tabstop=4

" Multiline indenting
set breakindent

" Traverse back with arrows
set whichwrap=b,s,<,>,[,]

" Start interactive EasyAlign in visual mode (e.g. vipga)
xmap ga <Plug>(EasyAlign)

" Start interactive EasyAlign for a motion/text object (e.g. gaip)
nmap ga <Plug>(EasyAlign)

" It's a real bitch but this will make you actually learn vim
no <up> <Nop>
no <down> <Nop>
no <left> <Nop>
no <right> <Nop>

ino <up> <Nop>
ino <down> <Nop>
ino <left> <Nop>
ino <right> <Nop>
