export PROMPT='$(vi_mode_status)'
export SAVEHIST=1000000
export HISTFILE=$HOME/.history
export HISTSIZE=1000000
export TERMINAL="/bin/alacritty"
export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'
export LESS='--use-color -IR'
export TERM='xterm-256color'
export SVDIR=$HOME/.service/
export GPG_TTY=$(tty)
export NNN_OPTS='arC'
export NNN_COLORS='4444'
export NNN_BMS="d:$HOME/docs;h:$HOME;g:$HOME/g;t:$HOME/tmp;m:/run/media/kota;M:/mnt"
export NNN_PLUG='x:!chmod +x $nnn;r:fixname;d:xdgdefault;j:autojump;p:preview-tui'
export XDG_CURRENT_DESKTOP='gnome' # Use gnome's file select dialogs.
export PF_INFO="ascii title os kernel uptime pkgs memory editor palette"
export CGO_ENABLED=1
export PCFSERVER='https://paste.nilsu.org:21/incoming'
export FZF_DEFAULT_COMMAND='rg --files'
export AART_VIEWER='sxiv -b -g 640x640'
export GOPATH="$HOME/go"
export PERL_BASE="$HOME/.local/perl5"
export PERL5LIB="$PERL_BASE/lib/perl5"
export LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib:$HOME/.local/lib:$LD_LIBRARY_PATH
export DENO_INSTALL="/home/kota/.deno"
export NPM_PACKAGES="${HOME}/.npm-packages"
export MANPAGER='less -Dd+g -Du+b'
export MANPATH="$NPM_PACKAGES/share/man:$HOME/.local/perl5/man:$MANPATH"
export PATH="$DENO_INSTALL/bin:$HOME/.local/perl5/bin:$GOPATH/bin:$NPM_PACKAGES/bin:$HOME/.cargo/bin:$HOME/bin:$HOME/.local/bin:$HOME/.luarocks/bin:$HOME/.nimble/bin:$PATH"
