export PROMPT='$(vi_mode_status)'
export SAVEHIST=1000000
export HISTFILE=$HOME/.history
export HISTSIZE=1000000
export TERMINAL="/bin/foot"
export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'
export LESS='--use-color -IR'
export TERM='xterm-256color'
export SVDIR=$HOME/.service/
export NNN_OPTS='aC'
export NNN_COLORS='4444'
export NNN_BMS="d:$HOME/docs;h:$HOME;g:$HOME/g;t:$HOME/tmp;m:/run/media/kota;M:/mnt"
export NNN_PLUG='x:!chmod +x $nnn;r:fixname;d:xdgdefault;j:autojump;p:preview-tui'
export XDG_CURRENT_DESKTOP='gnome' # Use gnome's file select dialogs.
export PF_INFO="ascii title os kernel uptime pkgs memory editor palette"
export CGO_ENABLED=1
export PCFSERVER='https://paste.nilsu.org:21/incoming'
export FZF_DEFAULT_COMMAND='rg --files'
export AART_VIEWER='imv'
export QT_QPA_PLATFORM=wayland-egl
export ELM_DISPLAY=wl
export SDL_VIDEODRIVER=wayland
export MOZ_ENABLE_WAYLAND=1
export GOPATH="$HOME/go"
export NPM_PACKAGES="${HOME}/.npm-packages"
export LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib:$HOME/.local/lib:$LD_LIBRARY_PATH
export MANPAGER='less -Dd+g -Du+b'
export MANPATH="$NPM_PACKAGES/share/man:$MANPATH"
export PATH="$GOPATH/bin:$NPM_PACKAGES/bin:$HOME/bin:$HOME/.local/bin:$PATH"
