directory: ~/music
library: ~/.local/share/beet/library.db
plugins: fetchart missing fromfilename convert
import:
  timid: yes
paths:
  default: $albumartist/[$year-$month-$day] $album%aunique{}/$track - $title
  singleton: $artist/Singles/$title
  comp: Various Artists/$album%aunique{}/$track - $title
convert:
  never_convert_lossy_files: yes
  extension: mp3
