directory: ~/music
library: ~/.local/share/beet/library.db
plugins: fetchart embedart lastgenre missing fromfilename convert
import:
  move: yes
paths:
  default: $albumartist/$album%aunique{}/$track $title
  singleton: $artist/Singles/$title
  comp: Compilations/$album%aunique{}/$track $title
  albumtype:soundtrack: Soundtracks/$album/$track $title
convert:
  never_convert_lossy_files: yes
  command: /home/kota/bin/gapless
  extension: mp3
